export const SELECT_CURRENCY = "SELECT_CURRENCY";
export const RECEIVE_TICKERS = "RECEIVE_TICKERS";
export const RECEIVE_OVERVIEW = "RECEIVE_OVERVIEW";
export const RECEIVE_HISTORY = "RECEIVE_HISTORY";
export const REQUEST_DATA = "REQUEST_DATA";
export const REQUEST_FAILED = "REQUEST_FAILED";
export const SET_SELECTED = "SET_SELECTED";
