// API Action Types
export const RECEIVE_TICKERS = "RECEIVE_TICKERS";
export const RECEIVE_COIN_DATA = "RECEIVE_COIN_DATA";
export const RECEIVE_MARKET_OVERVIEW_DATA = "RECEIVE_MARKET_OVERVIEW_DATA";
export const RECEIVE_COIN_HISTORY_DATA = "RECEIVE_COIN_HISTORY_DATA";
export const REQUEST_DATA = "REQUEST_DATA";
export const REQUEST_SUCCESSFUL = "REQUEST_SUCCESSFUL";
export const REQUEST_FAILED = "REQUEST_FAILED";

// Option Action Types
export const SET_SELECTED = "SET_SELECTED";
export const SELECT_CURRENCY = "SELECT_CURRENCY";
