// API Action Types
export const FETCH_TOP_TEN_REQUEST = "FETCH_TOP_TEN_REQUEST";
export const FETCH_TOP_TEN_SUCCESS = "FETCH_TOP_TEN_SUCCESS";
export const FETCH_TOP_TEN_FAILED = "FETCH_TOP_TEN_FAILED";

export const FETCH_COIN_HISTORY_REQUEST = "FETCH_COIN_HISTORY_REQUEST";
export const FETCH_COIN_HISTORY_SUCCESS = "FETCH_COIN_HISTORY_SUCCESS";
export const FETCH_COIN_HISTORY_FAILED = "FETCH_COIN_HISTORY_FAILED";

export const RECEIVE_TICKERS = "RECEIVE_TICKERS";
export const RECEIVE_COIN_DATA = "RECEIVE_COIN_DATA";
export const RECEIVE_MARKET_OVERVIEW_DATA = "RECEIVE_MARKET_OVERVIEW_DATA";
export const RECEIVE_COIN_HISTORY_DATA = "RECEIVE_COIN_HISTORY_DATA";

// Option Action Types
export const SET_SELECTED = "SET_SELECTED";
export const SELECT_CURRENCY = "SELECT_CURRENCY";

export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const FETCH_USER = "FETCH_USER";

export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";